import './globals.css'
import { Inter } from 'next/font/google'

import { AuthProvider } from './AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
}

export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className} {...props} />
      </AuthProvider>
    </html>
  )
}
